---@meta

---@class UAB_Ladybug01_C : UCharacterAnimInstance
---@field UberGraphFrame FPointerToUberGraphFrame
---@field AnimGraphNode_Root FAnimNode_Root
---@field AnimGraphNode_TransitionResult_10 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_9 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_8 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_7 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_6 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_5 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_4 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_3 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_2 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_1 FAnimNode_TransitionResult
---@field AnimGraphNode_SequencePlayer_4 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_5 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_3 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_4 FAnimNode_StateResult
---@field AnimGraphNode_BlendSpacePlayer FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_StateResult_3 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_2 FAnimNode_SequencePlayer
---@field AnimGraphNode_BlendListByBool_2 FAnimNode_BlendListByBool
---@field AnimGraphNode_RandomPlayer FAnimNode_RandomPlayer
---@field AnimGraphNode_StateResult_2 FAnimNode_StateResult
---@field AnimGraphNode_StateMachine_1 FAnimNode_StateMachine
---@field AnimGraphNode_Slot_1 FAnimNode_Slot
---@field AnimGraphNode_Slot FAnimNode_Slot
---@field AnimGraphNode_BlendListByBool_1 FAnimNode_BlendListByBool
---@field AnimGraphNode_ApplyAdditive FAnimNode_ApplyAdditive
---@field AnimGraphNode_TransitionResult FAnimNode_TransitionResult
---@field AnimGraphNode_SequencePlayer_1 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_1 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult FAnimNode_StateResult
---@field AnimGraphNode_StateMachine FAnimNode_StateMachine
---@field AnimGraphNode_PowerIK_Ground FAnimNode_PowerIK_Ground
---@field AnimGraphNode_LocalToComponentSpace FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_ComponentToLocalSpace FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_SaveCachedPose FAnimNode_SaveCachedPose
---@field AnimGraphNode_UseCachedPose_1 FAnimNode_UseCachedPose
---@field AnimGraphNode_BlendListByBool FAnimNode_BlendListByBool
---@field AnimGraphNode_UseCachedPose FAnimNode_UseCachedPose
---@field OwnerRef APawn
UAB_Ladybug01_C = {}

---@param AnimGraph FPoseLink
function UAB_Ladybug01_C:AnimGraph(AnimGraph) end
function UAB_Ladybug01_C:EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Ladybug01_AnimGraphNode_PowerIK_Ground_AC97C00F49DD375AD5E2FAAECC2160E1() end
function UAB_Ladybug01_C:EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Ladybug01_AnimGraphNode_TransitionResult_CB11F7364396A7FA4FEB2F8555C66888() end
function UAB_Ladybug01_C:EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Ladybug01_AnimGraphNode_TransitionResult_02BED65045F92644675E0099C3470489() end
function UAB_Ladybug01_C:EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Ladybug01_AnimGraphNode_TransitionResult_5F75D4D047FBAE01C968E6BE7EC2F1F9() end
function UAB_Ladybug01_C:EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Ladybug01_AnimGraphNode_TransitionResult_A303F7074376E439D32C96911321D584() end
function UAB_Ladybug01_C:EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Ladybug01_AnimGraphNode_TransitionResult_185AFD51489443C6AA3023AC81B136A2() end
function UAB_Ladybug01_C:EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Ladybug01_AnimGraphNode_TransitionResult_C55EC9474A0DCE9B585DE5A5C98AC070() end
function UAB_Ladybug01_C:AnimNotify_IdleVO() end
---@param EntryPoint int32
function UAB_Ladybug01_C:ExecuteUbergraph_AB_Ladybug01(EntryPoint) end


