---@meta

---@class UAB_Spider_C : UCharacterAnimInstance
---@field UberGraphFrame FPointerToUberGraphFrame
---@field AnimGraphNode_Root FAnimNode_Root
---@field AnimGraphNode_TransitionResult_11 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_10 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_9 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_8 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_7 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_6 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_5 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_4 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_3 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_2 FAnimNode_TransitionResult
---@field AnimGraphNode_SequencePlayer_5 FAnimNode_SequencePlayer
---@field AnimGraphNode_BlendListByBool_5 FAnimNode_BlendListByBool
---@field AnimGraphNode_SequencePlayer_4 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_5 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_3 FAnimNode_SequencePlayer
---@field AnimGraphNode_BlendListByBool_4 FAnimNode_BlendListByBool
---@field AnimGraphNode_SequencePlayer_2 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_4 FAnimNode_StateResult
---@field AnimGraphNode_RandomPlayer_1 FAnimNode_RandomPlayer
---@field AnimGraphNode_BlendListByBool_3 FAnimNode_BlendListByBool
---@field AnimGraphNode_SequencePlayer_1 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_3 FAnimNode_StateResult
---@field AnimGraphNode_BlendSpacePlayer FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_StateResult_2 FAnimNode_StateResult
---@field AnimGraphNode_StateMachine_1 FAnimNode_StateMachine
---@field AnimGraphNode_Slot_1 FAnimNode_Slot
---@field AnimGraphNode_Slot FAnimNode_Slot
---@field AnimGraphNode_BlendListByBool_2 FAnimNode_BlendListByBool
---@field AnimGraphNode_ApplyAdditive FAnimNode_ApplyAdditive
---@field AnimGraphNode_TransitionResult_1 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult FAnimNode_TransitionResult
---@field AnimGraphNode_RandomPlayer FAnimNode_RandomPlayer
---@field AnimGraphNode_StateResult_1 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult FAnimNode_StateResult
---@field AnimGraphNode_StateMachine FAnimNode_StateMachine
---@field AnimGraphNode_PowerIK_Ground FAnimNode_PowerIK_Ground
---@field AnimGraphNode_LocalToComponentSpace FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_ComponentToLocalSpace FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_SaveCachedPose FAnimNode_SaveCachedPose
---@field AnimGraphNode_UseCachedPose_2 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_1 FAnimNode_UseCachedPose
---@field AnimGraphNode_BlendListByBool_1 FAnimNode_BlendListByBool
---@field AnimGraphNode_BlendListByBool FAnimNode_BlendListByBool
---@field AnimGraphNode_UseCachedPose FAnimNode_UseCachedPose
---@field IsIdleCombat boolean
---@field ['Owner Ref'] APawn
UAB_Spider_C = {}

---@param AnimGraph FPoseLink
function UAB_Spider_C:AnimGraph(AnimGraph) end
function UAB_Spider_C:EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Spider_AnimGraphNode_PowerIK_Ground_BA256094443895DEE0C64CB090276D05() end
function UAB_Spider_C:EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Spider_AnimGraphNode_TransitionResult_D24AFAE640C44FB3742565B30FB8C037() end
function UAB_Spider_C:EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Spider_AnimGraphNode_SequencePlayer_E1ED5AF2435A193F65E005A6789C8FF7() end
function UAB_Spider_C:EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Spider_AnimGraphNode_SequencePlayer_C0AF729A4A9A7F0BAE124097FC556FE4() end
function UAB_Spider_C:EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Spider_AnimGraphNode_SequencePlayer_E96C665F4CB01FDDBE896FB84CFA9CFE() end
function UAB_Spider_C:EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Spider_AnimGraphNode_SequencePlayer_B52CF8DA406921998156298E49456920() end
function UAB_Spider_C:EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Spider_AnimGraphNode_TransitionResult_D09005C24985B97FD5D9939D9E8840A9() end
function UAB_Spider_C:EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Spider_AnimGraphNode_TransitionResult_3C14A986408334917E1F7785EF2249A9() end
function UAB_Spider_C:EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Spider_AnimGraphNode_TransitionResult_EAAAD1F54840A12EEF30F298306E4DDE() end
function UAB_Spider_C:EvaluateGraphExposedInputs_ExecuteUbergraph_AB_Spider_AnimGraphNode_TransitionResult_24855585421173E8C1CDAD817664F618() end
function UAB_Spider_C:AnimNotify_IdleVO() end
---@param EntryPoint int32
function UAB_Spider_C:ExecuteUbergraph_AB_Spider(EntryPoint) end


