---@meta

---@class AAR_16_Undershed_Design_Actors_C : ALevelScriptActor
---@field UberGraphFrame FPointerToUberGraphFrame
---@field ['Other Actor'] AActor
---@field BP_Lab_Door_A70_33_ExecuteUbergraph_AR_16_Undershed_Design_Actors_RefProperty ABP_Lab_Door_A_C
---@field BP_BossManager_Mant_ExecuteUbergraph_AR_16_Undershed_Design_Actors_RefProperty ABP_BossManager_C
---@field BP_Lab_Door_Freezer_2_ExecuteUbergraph_AR_16_Undershed_Design_Actors_RefProperty ABP_Lab_Door_Freezer_C
AAR_16_Undershed_Design_Actors_C = {}

function AAR_16_Undershed_Design_Actors_C:BndEvt__AR_16_Undershed_Design_Actors_BP_Biometric_Switch_UndershedGate_2_K2Node_ActorBoundEvent_0_OnBiometricScanned__DelegateSignature() end
---@param TriggerActor AActor
---@param OtherActor AActor
function AAR_16_Undershed_Design_Actors_C:BndEvt__AR_16_Undershed_Design_Actors_MaineTriggerBox_1_K2Node_ActorBoundEvent_1_TriggerDelegate__DelegateSignature(TriggerActor, OtherActor) end
function AAR_16_Undershed_Design_Actors_C:BndEvt__AR_16_Undershed_Design_Actors_BP_UndershedLab_Door_Manager_2_K2Node_ActorBoundEvent_3_WendellOpensDoor01__DelegateSignature() end
function AAR_16_Undershed_Design_Actors_C:BndEvt__AR_16_Undershed_Design_Actors_BP_UndershedLab_Door_Manager_2_K2Node_ActorBoundEvent_4_WendellOpensDoor02__DelegateSignature() end
---@param TriggerActor AActor
---@param OtherActor AActor
function AAR_16_Undershed_Design_Actors_C:BndEvt__AR_16_Undershed_Design_Actors_MaineTriggerSphere_UpdatedFindWendell_K2Node_ActorBoundEvent_5_TriggerDelegate__DelegateSignature(TriggerActor, OtherActor) end
---@param OverlappedActor AActor
---@param OtherActor AActor
function AAR_16_Undershed_Design_Actors_C:BndEvt__AR_16_Undershed_Design_Actors_MantTrigger_K2Node_ActorBoundEvent_6_ActorBeginOverlapSignature__DelegateSignature(OverlappedActor, OtherActor) end
---@param ActorDamageSource AActor
function AAR_16_Undershed_Design_Actors_C:BndEvt__AR_16_Undershed_Design_Actors_BP_BossManager_Mant_K2Node_ActorBoundEvent_7_BossCompleteDelegate__DelegateSignature(ActorDamageSource) end
function AAR_16_Undershed_Design_Actors_C:BndEvt__AR_16_Undershed_Design_Actors_BP_BossManager_Mant_K2Node_ActorBoundEvent_10_BossActivateDelegate__DelegateSignature() end
function AAR_16_Undershed_Design_Actors_C:BndEvt__AR_16_Undershed_Design_Actors_BP_BossManager_Mant_K2Node_ActorBoundEvent_11_BossActivateDelegate__DelegateSignature() end
---@param TriggerActor AActor
---@param OtherActor AActor
function AAR_16_Undershed_Design_Actors_C:BndEvt__AR_16_Undershed_Design_Actors_MaineTriggerBox_3_K2Node_ActorBoundEvent_1_TriggerDelegate__DelegateSignature(TriggerActor, OtherActor) end
---@param OverlappedActor AActor
---@param OtherActor AActor
function AAR_16_Undershed_Design_Actors_C:BndEvt__AR_16_Undershed_Design_Actors_MaineTriggerBox_2_K2Node_ActorBoundEvent_2_ActorBeginOverlapSignature__DelegateSignature(OverlappedActor, OtherActor) end
---@param TriggerActor AActor
---@param OtherActor AActor
function AAR_16_Undershed_Design_Actors_C:BndEvt__AR_16_Undershed_Design_Actors_MaineTriggerSphere_SinkholePOI_K2Node_ActorBoundEvent_9_TriggerDelegate__DelegateSignature(TriggerActor, OtherActor) end
---@param EntryPoint int32
function AAR_16_Undershed_Design_Actors_C:ExecuteUbergraph_AR_16_Undershed_Design_Actors(EntryPoint) end


