---@meta

---@class AAR_21_StorageLab_DesignActors_C : ALevelScriptActor
---@field UberGraphFrame FPointerToUberGraphFrame
---@field BP_Lab_Door_A93_2_ExecuteUbergraph_AR_21_StorageLab_DesignActors_RefProperty ABP_Lab_Door_A_C
AAR_21_StorageLab_DesignActors_C = {}

function AAR_21_StorageLab_DesignActors_C:BndEvt__AR_21_StorageLab_DesignActors_BP_JavamatchStash_LabDoor_Manager_2_K2Node_ActorBoundEvent_0_WendellOpensDoor01__DelegateSignature() end
---@param EntryPoint int32
function AAR_21_StorageLab_DesignActors_C:ExecuteUbergraph_AR_21_StorageLab_DesignActors(EntryPoint) end


