---@meta

---@class AAR_21_DefensePoint_Design_Actors_C : ALevelScriptActor
---@field UberGraphFrame FPointerToUberGraphFrame
---@field ['End Play Reason'] EEndPlayReason::Type
---@field BP_BlenderStartSwitch_2_ExecuteUbergraph_AR_21_DefensePoint_Design_Actors_RefProperty ABP_BlenderStartSwitch_C
---@field BP_TEST_Wire_B_ExecuteUbergraph_AR_21_DefensePoint_Design_Actors_RefProperty ABP_TEST_WIRE_B_C
---@field BP_TEST_WIRE_C_ExecuteUbergraph_AR_21_DefensePoint_Design_Actors_RefProperty ABP_TEST_WIRE_C_C
---@field BP_Wendell_Speaker3_ExecuteUbergraph_AR_21_DefensePoint_Design_Actors_RefProperty ABP_Wendell_Speaker_C
---@field BP_JavamaticDefensePointManager_ExecuteUbergraph_AR_21_DefensePoint_Design_Actors_RefProperty ABP_TestDefensePointManager_C
---@field SM_CoffeeMaker_Calculator_63_ExecuteUbergraph_AR_21_DefensePoint_Design_Actors_RefProperty ABP_CoffeMaker_Calculator_C
---@field Encounter7_ExecuteUbergraph_AR_21_DefensePoint_Design_Actors_RefProperty AEncounter
---@field Encounter8_ExecuteUbergraph_AR_21_DefensePoint_Design_Actors_RefProperty AEncounter
---@field Encounter_1_ExecuteUbergraph_AR_21_DefensePoint_Design_Actors_RefProperty AEncounter
---@field BP_KeyedInteraction_BlenderUltraCapacitor_2_ExecuteUbergraph_AR_21_DefensePoint_Design_Actors_RefProperty ABP_KeyedInteraction_BlenderUltraCapacitor_C
AAR_21_DefensePoint_Design_Actors_C = {}

function AAR_21_DefensePoint_Design_Actors_C:DEBUG_StartJavaDefense() end
---@param TriggerActor AActor
---@param OtherActor AActor
function AAR_21_DefensePoint_Design_Actors_C:BndEvt__AR_21_DefensePoint_Design_Actors_MaineTriggerBox4_K2Node_ActorBoundEvent_1_TriggerDelegate__DelegateSignature(TriggerActor, OtherActor) end
---@param bSuccess boolean
function AAR_21_DefensePoint_Design_Actors_C:BndEvt__AR_21_DefensePoint_Design_Actors_BP_TestDefensePointManager_2_K2Node_ActorBoundEvent_4_DefensePointCompleteDelegate__DelegateSignature(bSuccess) end
function AAR_21_DefensePoint_Design_Actors_C:DEBUG_JavaPowerCS() end
---@param IsOpen boolean
---@param Instigator AActor
function AAR_21_DefensePoint_Design_Actors_C:BndEvt__AR_21_DefensePoint_Design_Actors_BP_KeyedInteraction_BlenderUltraCapacitor_2_K2Node_ActorBoundEvent_5_OpenStateChangedDelegate__DelegateSignature(IsOpen, Instigator) end
---@param IsOpen boolean
---@param Instigator AActor
function AAR_21_DefensePoint_Design_Actors_C:BndEvt__AR_21_DefensePoint_Design_Actors_BP_BlenderStartSwitch_2_K2Node_ActorBoundEvent_3_OpenStateChangedDelegate__DelegateSignature(IsOpen, Instigator) end
function AAR_21_DefensePoint_Design_Actors_C:DEBUG_JavaFinishCS() end
function AAR_21_DefensePoint_Design_Actors_C:BndEvt__AR_21_DefensePoint_Design_Actors_BP_MicroSolution_RecipeSlot_2_K2Node_ActorBoundEvent_0_GrindAudioFinished__DelegateSignature() end
---@param ChargeRatio float
function AAR_21_DefensePoint_Design_Actors_C:BndEvt__AR_21_DefensePoint_Design_Actors_BP_JavamaticDefensePointManager_K2Node_ActorBoundEvent_2_DefensePointChargeDelegate__DelegateSignature(ChargeRatio) end
---@param OverlappedActor AActor
---@param OtherActor AActor
function AAR_21_DefensePoint_Design_Actors_C:BndEvt__AR_21_DefensePoint_Design_Actors_Trigger_Backpack_Spawn2_K2Node_ActorBoundEvent_6_ActorBeginOverlapSignature__DelegateSignature(OverlappedActor, OtherActor) end
---@param OverlappedActor AActor
---@param OtherActor AActor
function AAR_21_DefensePoint_Design_Actors_C:BndEvt__AR_21_DefensePoint_Design_Actors_Trigger_Backpack_Spawn3_K2Node_ActorBoundEvent_8_ActorBeginOverlapSignature__DelegateSignature(OverlappedActor, OtherActor) end
---@param OverlappedActor AActor
---@param OtherActor AActor
function AAR_21_DefensePoint_Design_Actors_C:BndEvt__AR_21_DefensePoint_Design_Actors_Trigger_Backpack_Spawn4_K2Node_ActorBoundEvent_11_ActorBeginOverlapSignature__DelegateSignature(OverlappedActor, OtherActor) end
---@param EntryPoint int32
function AAR_21_DefensePoint_Design_Actors_C:ExecuteUbergraph_AR_21_DefensePoint_Design_Actors(EntryPoint) end


