---@meta

---@class ABP_Control_Panel_Standing_AllDefensePointsComplete_C : ABP_Control_Panel_Standing_C
---@field UberGraphFrame FPointerToUberGraphFrame
---@field ConditionalToggle_DefensePoint_08 UConditionalToggleComponent
---@field ConditionalToggle_DefensePoint_07 UConditionalToggleComponent
---@field ConditionalToggle_DefensePoint_06 UConditionalToggleComponent
---@field ConditionalToggle_DefensePoint_05 UConditionalToggleComponent
---@field ConditionalToggle_DefensePoint_04 UConditionalToggleComponent
---@field ConditionalToggle_DefensePoint_03 UConditionalToggleComponent
---@field ConditionalToggle_DefensePoint_02 UConditionalToggleComponent
---@field ConditionalToggle_DefensePoint_01 UConditionalToggleComponent
---@field ConditionalToggle_DefensePointsAllComplete UConditionalToggleComponent
---@field Timeline_1_Driver_3F7BBAA842EB0624549E169E92E0C0B1 float
---@field Timeline_1__Direction_3F7BBAA842EB0624549E169E92E0C0B1 ETimelineDirection::Type
---@field Timeline_1 UTimelineComponent
---@field Timeline_0_Driver_08C5E7BC442A0BF105A5C78AB77A46A5 float
---@field Timeline_0__Direction_08C5E7BC442A0BF105A5C78AB77A46A5 ETimelineDirection::Type
---@field Timeline_0 UTimelineComponent
ABP_Control_Panel_Standing_AllDefensePointsComplete_C = {}

function ABP_Control_Panel_Standing_AllDefensePointsComplete_C:IncrementMIXRProgress() end
function ABP_Control_Panel_Standing_AllDefensePointsComplete_C:Timeline_0__FinishedFunc() end
function ABP_Control_Panel_Standing_AllDefensePointsComplete_C:Timeline_0__UpdateFunc() end
function ABP_Control_Panel_Standing_AllDefensePointsComplete_C:Timeline_1__FinishedFunc() end
function ABP_Control_Panel_Standing_AllDefensePointsComplete_C:Timeline_1__UpdateFunc() end
---@param bIsActive boolean
function ABP_Control_Panel_Standing_AllDefensePointsComplete_C:BndEvt__BP_Control_Panel_Standing_AllDefensePointsComplete_ConditionalToggle_DefensePointsAllComplete_K2Node_ComponentBoundEvent_0_OnConditionalStateChanged__DelegateSignature(bIsActive) end
---@param bIsActive boolean
function ABP_Control_Panel_Standing_AllDefensePointsComplete_C:BndEvt__BP_Control_Panel_Standing_AllDefensePointsComplete_ConditionalToggle_AnyComplete_K2Node_ComponentBoundEvent_1_OnConditionalStateChanged__DelegateSignature(bIsActive) end
---@param bIsActive boolean
function ABP_Control_Panel_Standing_AllDefensePointsComplete_C:BndEvt__BP_Control_Panel_Standing_AllDefensePointsComplete_ConditionalToggle_DefensePoint_02_K2Node_ComponentBoundEvent_2_OnConditionalStateChanged__DelegateSignature(bIsActive) end
---@param bIsActive boolean
function ABP_Control_Panel_Standing_AllDefensePointsComplete_C:BndEvt__BP_Control_Panel_Standing_AllDefensePointsComplete_ConditionalToggle_DefensePoint_03_K2Node_ComponentBoundEvent_3_OnConditionalStateChanged__DelegateSignature(bIsActive) end
---@param bIsActive boolean
function ABP_Control_Panel_Standing_AllDefensePointsComplete_C:BndEvt__BP_Control_Panel_Standing_AllDefensePointsComplete_ConditionalToggle_DefensePoint_04_K2Node_ComponentBoundEvent_4_OnConditionalStateChanged__DelegateSignature(bIsActive) end
---@param bIsActive boolean
function ABP_Control_Panel_Standing_AllDefensePointsComplete_C:BndEvt__BP_Control_Panel_Standing_AllDefensePointsComplete_ConditionalToggle_DefensePoint_05_K2Node_ComponentBoundEvent_5_OnConditionalStateChanged__DelegateSignature(bIsActive) end
---@param bIsActive boolean
function ABP_Control_Panel_Standing_AllDefensePointsComplete_C:BndEvt__BP_Control_Panel_Standing_AllDefensePointsComplete_ConditionalToggle_DefensePoint_06_K2Node_ComponentBoundEvent_6_OnConditionalStateChanged__DelegateSignature(bIsActive) end
---@param bIsActive boolean
function ABP_Control_Panel_Standing_AllDefensePointsComplete_C:BndEvt__BP_Control_Panel_Standing_AllDefensePointsComplete_ConditionalToggle_DefensePoint_07_K2Node_ComponentBoundEvent_7_OnConditionalStateChanged__DelegateSignature(bIsActive) end
---@param bIsActive boolean
function ABP_Control_Panel_Standing_AllDefensePointsComplete_C:BndEvt__BP_Control_Panel_Standing_AllDefensePointsComplete_ConditionalToggle_DefensePoint_08_K2Node_ComponentBoundEvent_8_OnConditionalStateChanged__DelegateSignature(bIsActive) end
function ABP_Control_Panel_Standing_AllDefensePointsComplete_C:ReceiveBeginPlay() end
---@param IsOpen boolean
function ABP_Control_Panel_Standing_AllDefensePointsComplete_C:OnUpdateVisualState(IsOpen) end
---@param EntryPoint int32
function ABP_Control_Panel_Standing_AllDefensePointsComplete_C:ExecuteUbergraph_BP_Control_Panel_Standing_AllDefensePointsComplete(EntryPoint) end


