---@meta

---@class ABP_TimeOfDayLighting_C : ATimeOfDayLightingManager
---@field UberGraphFrame FPointerToUberGraphFrame
---@field SunLight UDirectionalLightComponent
---@field PostProcessMain UPostProcessComponent
---@field MoonLight UDirectionalLightComponent
---@field Root USceneComponent
---@field CausticsFadeIn_NewTrack_0_A35833A344AEC615A640D888D43D4851 float
---@field CausticsFadeIn__Direction_A35833A344AEC615A640D888D43D4851 ETimelineDirection::Type
---@field CausticsFadeIn UTimelineComponent
---@field TL_HourlyPostProcessTransition_PPValue_E0358A0249856464FD5D9198D289FD56 float
---@field TL_HourlyPostProcessTransition__Direction_E0358A0249856464FD5D9198D289FD56 ETimelineDirection::Type
---@field TL_HourlyPostProcessTransition UTimelineComponent
---@field SkyLight ASkyLight
---@field SetTime float
---@field VolumetricFogThicknessPreview float
---@field WaterMoonMultiplier float
---@field WaterSunMultiplier float
---@field WaterSkylightMultiplier float
---@field IndoorPrev float
---@field Moon boolean
---@field AtmosphericFog AAtmosphericFog
---@field SkySphere ABP_Sky_Sphere_2_C
---@field ExponentialHeightFog AExponentialHeightFog
---@field MaxBrightnessOutdoor float
---@field MinBrightnessOutdoor float
---@field FogMultiplierRandom float
---@field SunDiscColorMultiplier float
---@field SunPosHorizon float
---@field BlendIntensity float
---@field SkyLightBlendStrength float
---@field SkylightMax float
---@field InteriorDaylightStrength float
---@field HedgeVolumetricScatter float
---@field SkylightColorTint FLinearColor
---@field SunContribution boolean
---@field MoonContribution boolean
---@field FogContribution boolean
---@field HedgeContribution boolean
---@field HourlyIntensity float
---@field HedgeMoonIntensity float
---@field CurrentHour int32
---@field SunIntensityCurve UCurveFloat
---@field MoonIntensityCurve UCurveFloat
---@field MoonFadeCurve UCurveFloat
---@field SunTemperatureCurve UCurveFloat
---@field SunDiscColorCurve UCurveLinearColor
---@field FogExtinctionCurve UCurveFloat
---@field AtmosFogColorCurve UCurveLinearColor
---@field SkyLightCubemapCurve UCurveFloat
---@field SkyLightCubemapTranslucentCurve UCurveFloat
---@field SkyLightFilterCurve UCurveLinearColor
---@field LootableIntensityCurve UCurveFloat
---@field FogVolumes TArray<AActor>
---@field PostProcessVolumes TArray<APostProcessVolume>
---@field VolumetricFogScales TArray<FVector>
---@field UnderWater boolean
---@field MoonPresence boolean
---@field Calendar UCalendarComponent
---@field OncePerDay boolean
---@field DirtSpecularCurve UCurveFloat
---@field FogSkylightScatterCurve UCurveFloat
---@field InteriorDaylightColorCurve UCurveLinearColor
---@field HorizonColorCurve UCurveLinearColor
---@field ZenithColorCurve UCurveLinearColor
---@field WaterBallEmissiveCurve UCurveLinearColor
---@field HedgeSkylightCurve UCurveFloat
---@field VolumetricFogs FName
---@field InteriorDaylight FName
---@field InteriorDaylightContribution boolean
---@field PostProcessContribution boolean
---@field PostProcessDayNight FName
---@field Lights boolean
---@field IndoorPreview boolean
---@field HedgePreview boolean
---@field PreviousIndoorPreview boolean
---@field InteriorDaylightBackground FName
---@field InteriorDaylights TArray<ABP_Custom_Indirect_Spotlight_C>
---@field InteriorLightBGMIDs TArray<UMaterialInstanceDynamic>
---@field CubemapSlot0 UTextureCube
---@field CubemapSlot1 UTextureCube
---@field EnvironmentCube_Midnight UTextureCube
---@field EnvironmentCube_Sunrise UTextureCube
---@field EnvironmentCube_Noon UTextureCube
---@field EnvironmentCube_Sunset UTextureCube
---@field WaterlineColorCurve UCurveLinearColor
---@field SunOcclusionMaskCurve UCurveFloat
---@field PlayerSetDOF boolean
---@field PostProcessClass TSubclassOf<APostProcessVolume>
---@field MeshComponentClass TSubclassOf<UMeshComponent>
---@field LightComponentClass TSubclassOf<ULightComponent>
---@field NightEmissiveClass TSubclassOf<ABP_NightEmissveBase_C>
---@field VolumetricInscatterSunCurve UCurveFloat
---@field DOF boolean
---@field CloudColorCurve UCurveLinearColor
---@field CutsceneFogMultiplier float
---@field CubemapsDefault TArray<UTextureCube>
---@field CubemapsPond TArray<UTextureCube>
---@field CubemapsPondSoft TArray<TSoftObjectPtr<UTextureCube>>
---@field BakePreparation boolean
---@field UsePondCubemaps boolean
---@field RT_Manager ABP_Landscape_RT_Manager_C
---@field ActorsUsingRT TArray<ABP_Water_Base_C>
---@field NearestWaterBP ABP_Water_Base_C
---@field NearestWaterBP_Prev ABP_Water_Base_C
---@field MID_LightFunction UMaterialInstanceDynamic
---@field MID_LightFunction_wCaustics UMaterialInstanceDynamic
---@field CausticsFadeCurAlpha float
---@field isBlendingCaustics boolean
---@field UnderwaterPreview boolean
---@field WaterSkylightIntensityCurve UCurveFloat
---@field HDR_Enabled boolean
---@field HDR_Sun_Multiplier float
---@field HDR_Sky_Multiplier float
---@field HDR_SunDisc_Multiplier float
---@field HDR_Moon_Multiplier float
---@field HDR_MoonDisc_Multiplier float
---@field HDR_CloudOpacity_Multiplier float
---@field HDR_SunDisc_BloomScale_Multiplier float
---@field HDR_SkylightCurve UCurveFloat
---@field OakTreeUVOffset1 FVector
---@field OakTreeUVOffset2 FVector
---@field OakTreeWindSpeed1 float
---@field OakTreeWindSpeed2 float
---@field OakTreeWindStrength1 float
---@field OakTreeWindStrength2 float
---@field OakTreeShadowLeavesScale float
---@field GroundSpecularContribution boolean
---@field BlendTriggerArray TArray<ABP_BlendTrigger_C>
---@field BlendTriggerAttributesTOD FBlendTriggerAttributes
---@field CurrentTrigger ABP_BlendTrigger_C
---@field PreviousTrigger ABP_BlendTrigger_C
---@field DefaultBlendTriggerAttributes FBlendTriggerAttributes
---@field HighestPriorityBlendTrigger FBlendTriggerAttributes
---@field HasOakTreeShadow boolean
ABP_TimeOfDayLighting_C = {}

function ABP_TimeOfDayLighting_C:UpdateBlendTriggerPriority() end
function ABP_TimeOfDayLighting_C:SetPerFrameBlendSettings() end
---@param Intensity float
function ABP_TimeOfDayLighting_C:SetInteriorDaylightsIntensity(Intensity) end
---@param Intensity float
---@param Color FLinearColor
function ABP_TimeOfDayLighting_C:SetInteriorDaylightsColorAndIntensity(Intensity, Color) end
function ABP_TimeOfDayLighting_C:SetInUseValues() end
---@return AActor
function ABP_TimeOfDayLighting_C:GetCurrentBlendTrigger() end
---@return UPostProcessComponent
function ABP_TimeOfDayLighting_C:GetPostProcessMain() end
---@return UDirectionalLightComponent
function ABP_TimeOfDayLighting_C:GetSunLight() end
---@param PreviousTrigger ABP_BlendTrigger_C
function ABP_TimeOfDayLighting_C:SetPreviousTrigger(PreviousTrigger) end
---@param BlendTriggerArray TArray<ABP_BlendTrigger_C>
---@param OutBlendTriggerArray TArray<ABP_BlendTrigger_C>
function ABP_TimeOfDayLighting_C:SortTriggerArrayByPriority(BlendTriggerArray, OutBlendTriggerArray) end
---@param BlendTrigger ABP_BlendTrigger_C
---@param Deregister boolean
function ABP_TimeOfDayLighting_C:RegisterBlendTrigger(BlendTrigger, Deregister) end
ABP_TimeOfDayLighting_C['Photo Mode Hourly Event Updates'] = function() end
---@param Current_Hour int32
ABP_TimeOfDayLighting_C['Get Current Hour'] = function(Current_Hour) end
function ABP_TimeOfDayLighting_C:UpdateOakTreeShadow() end
function ABP_TimeOfDayLighting_C:UpdatePostProcess() end
function ABP_TimeOfDayLighting_C:UpdateTransitions() end
function ABP_TimeOfDayLighting_C:UpdateCollections() end
function ABP_TimeOfDayLighting_C:UpdateVolumetricFog() end
function ABP_TimeOfDayLighting_C:UpdateSkylight() end
function ABP_TimeOfDayLighting_C:UpdateSky() end
function ABP_TimeOfDayLighting_C:UpdateMoon() end
function ABP_TimeOfDayLighting_C:UpdateSun() end
function ABP_TimeOfDayLighting_C:GetNearestWaterBounds() end
function ABP_TimeOfDayLighting_C:GetAllReferences() end
---@param NewIntensity float
function ABP_TimeOfDayLighting_C:SetBlendIntensity(NewIntensity) end
function ABP_TimeOfDayLighting_C:UserConstructionScript() end
function ABP_TimeOfDayLighting_C:TL_HourlyPostProcessTransition__FinishedFunc() end
function ABP_TimeOfDayLighting_C:TL_HourlyPostProcessTransition__UpdateFunc() end
function ABP_TimeOfDayLighting_C:CausticsFadeIn__FinishedFunc() end
function ABP_TimeOfDayLighting_C:CausticsFadeIn__UpdateFunc() end
function ABP_TimeOfDayLighting_C:ReceiveBeginPlay() end
---@param DeltaSeconds float
function ABP_TimeOfDayLighting_C:ReceiveTick(DeltaSeconds) end
---@param NewHour int32
---@param NewDay int32
function ABP_TimeOfDayLighting_C:CubemapSwap(NewHour, NewDay) end
---@param NewHour int32
---@param NewDay int32
function ABP_TimeOfDayLighting_C:UpdateHourlyVariables(NewHour, NewDay) end
---@param NewHour int32
---@param NewDay int32
function ABP_TimeOfDayLighting_C:DisableFog(NewHour, NewDay) end
---@param NewDay int32
function ABP_TimeOfDayLighting_C:UpdateDailyVariables(NewDay) end
---@param Angle float
function ABP_TimeOfDayLighting_C:SetSunAngle(Angle) end
function ABP_TimeOfDayLighting_C:ClearArrays() end
function ABP_TimeOfDayLighting_C:ToggleDOF() end
---@param Distance float
function ABP_TimeOfDayLighting_C:SetDOFDistance(Distance) end
---@param Radius float
function ABP_TimeOfDayLighting_C:SetDOFBlur(Radius) end
---@param Blur float
function ABP_TimeOfDayLighting_C:SetDOFDepthBlur(Blur) end
---@param Calendar UCalendarComponent
function ABP_TimeOfDayLighting_C:SetHourlyEvents(Calendar) end
function ABP_TimeOfDayLighting_C:SetHourlyPostProcess() end
---@param Calendar UCalendarComponent
function ABP_TimeOfDayLighting_C:SetSkylightCubemaps(Calendar) end
---@param Calendar UCalendarComponent
function ABP_TimeOfDayLighting_C:SetHourlyFogEvents(Calendar) end
---@param FogMultiplier float
function ABP_TimeOfDayLighting_C:SetCutsceneFog(FogMultiplier) end
---@param ViewDistanceOverride float
function ABP_TimeOfDayLighting_C:SetFoliageViewDistance(ViewDistanceOverride) end
function ABP_TimeOfDayLighting_C:SetPondCubemaps() end
function ABP_TimeOfDayLighting_C:SetDefaultCubemaps() end
ABP_TimeOfDayLighting_C['Set Water Caustic Masks'] = function() end
function ABP_TimeOfDayLighting_C:OnActiveBlendablesChanged() end
ABP_TimeOfDayLighting_C['Update Hourly Events'] = function() end
---@param Moonlight_Multiplier float
function ABP_TimeOfDayLighting_C:SetCutsceneMoonlight(Moonlight_Multiplier) end
function ABP_TimeOfDayLighting_C:RefreshBlendTriggerPriorities() end
---@param EntryPoint int32
function ABP_TimeOfDayLighting_C:ExecuteUbergraph_BP_TimeOfDayLighting(EntryPoint) end


