---@meta

---@class UUI_MainMenu_C : UMainMenuWidget
---@field UberGraphFrame FPointerToUberGraphFrame
---@field ShowHideDescription UWidgetAnimation
---@field ShowNews UWidgetAnimation
---@field MenuUnveal UWidgetAnimation
---@field BGAlphaAnimation UWidgetAnimation
---@field ShowMainMenuBGElements UWidgetAnimation
---@field NameAnim UWidgetAnimation
---@field ShowHostJoinBackward UWidgetAnimation
---@field ShowHostJoinForward UWidgetAnimation
---@field ShowNewContinueState UWidgetAnimation
---@field ShowMainMenuState UWidgetAnimation
---@field PanelUnload UWidgetAnimation
---@field PanelLoad UWidgetAnimation
---@field AccessibilityShortcutButton UUI_HotKeyButton_C
---@field AccountLinkWidgetSlot UHorizontalBox
---@field AlphaText ULocalizedTextBlock
---@field Background UImage
---@field Background_1 UImage
---@field Background_2 UImage
---@field Background_3 UImage
---@field BlackFader UImage
---@field ChangeProfileButton UUI_HotKeyButton_C
---@field CircularThrobber_65 UCircularThrobber
---@field CrossplayBorder UBorder
---@field CrossplayText ULocalizedTextBlock
---@field DemoModeCheckbox UCheckBox
---@field DemoModeText UTextBlock
---@field DisableCrossplayMainMenuButton UUI_HotKeyButton_C
---@field DisableCrossplayShortcutButton UUI_HotKeyButton_C
---@field EnableCrossplayMainMenuButton UUI_HotKeyButton_C
---@field EnableCrossplayShortcutButton UUI_HotKeyButton_C
---@field FadeInPanelBG UBorder
---@field fg_1 UImage
---@field Gnats UImage
---@field GrassFG UImage
---@field HazeBG UImage
---@field HazeBG_1 UImage
---@field HazeBG_2 UImage
---@field HazeBG_3 UImage
---@field Hornet1 UImage
---@field Interface UCanvasPanel
---@field Kids UImage
---@field Kids_1 UImage
---@field LogginInBG UImage
---@field NarrateMainMenu UBP_NarrateLocStringWidget_C
---@field PlatformHandleName UUI_LoggedInUserName_C
---@field ServerBrowserPanel UCanvasPanel
---@field Specks UImage
---@field Specks_1 UImage
---@field Spider UImage
---@field UI_GroundedTitle UUI_GroundedTitle_C
---@field UI_LimitedTime_MainMenu UUI_LimitedTime_MainMenu_C
---@field UI_MainMenuDescription UUI_MainMenuDescription_C
---@field UI_OnlineLogin UUI_OnlineLogin_C
---@field UI_WhatsNew_FullyYoked UUI_WhatsNew_FullyYoked_C
---@field UseLanCheckBox UCheckBox
---@field UseLanText UTextBlock
---@field VersionPlatformBox UVerticalBox
---@field VersionText UTextBlock
---@field WaitingVisuals UCanvasPanel
---@field WaitScreenText UTextBlock
---@field IsLoadingMap boolean
---@field OptionsIsOpen boolean
---@field ShowWaitingScreen boolean
---@field LoggingInString FLocString
---@field CreatingLobbyString FLocString
---@field HostFailureTitle FLocString
---@field HostFailureBody FLocString
---@field ConnectionFailureTitle FLocString
---@field ConnectionFailureBody FLocString
---@field YouGotKickedString FLocString
---@field ArachnophobiaTitleString FLocString
---@field ArachnophobiaTextString FLocString
---@field OKString FLocString
---@field GoToOptionsString FLocString
---@field SingleplayerString FLocString
---@field MultiplayerString FLocString
---@field WelcomeMessageString FLocString
---@field WelcomeMessageHeader FLocString
---@field MultiplayerPrivilegeTitle FLocString
---@field MultiplayerPrivilegeBody FLocString
---@field RequiresXboxLiveTitle FLocString
---@field RequiresXboxLiveBody FLocString
---@field MainMenuInputLocked boolean
---@field DisconnectedDuringPlayTitle FLocString
---@field DisconnectedDuringPlayBody FLocString
---@field ServerOffsetLargeTitle FLocString
---@field ServerOffsetLargeBody FLocString
---@field YesString FLocString
---@field NoString FLocString
---@field PasswordedGameQuestionTitle FLocString
---@field PasswordedGameQuestionBody FLocString
---@field SaveConversionStatusWindow UUI_ProgressBarPopup_C
---@field SaveConversionTitle FLocString
---@field SaveConversionBody FLocString
---@field UpdateRequiredTitle FLocString
---@field UpdateRequiredBody FLocString
---@field EnterPasswordBody FLocString
---@field MultiplayerContinueSelected boolean
---@field AccessibilityTitle FLocString
---@field AccessibilityBody FLocString
---@field IsEarlyAccessBuild boolean
---@field LoginFailure boolean
---@field NewsShown boolean
---@field LoggingInViaMultiplayerMenu boolean
---@field LoadGameType ESaveLoadGameTypeMode
---@field RequiresNintendoOnline FLocString
---@field RequiresPSN FLocString
---@field RequiresNintendoOnlineBody FLocString
---@field RequiresPSNBody FLocString
---@field NSOMissingTitle FLocString
---@field NSOMissingBody FLocString
---@field ['PS+MissingTitle'] FLocString
---@field ['PS+MissingBody'] FLocString
---@field AccountLinkWidgetRef UUI_AccountLink_C
---@field SaveLoadInterfaceRef UUI_SaveLoadInterface_C
---@field AgeRestrictionFailureTitle FLocString
---@field AgeRestrictionFailureBodyPS FLocString
---@field CrossplayEnabledText FLocString
---@field CrossplayDisabledText FLocString
---@field OptionsWindowWidgetRef UUI_Options_C
---@field SteamAccountLinkRef UUI_SteamAccountLink_C
UUI_MainMenu_C = {}

function UUI_MainMenu_C:UpdatePlatformHandleName() end
---@param Result boolean
UUI_MainMenu_C['Should Block Input'] = function(Result) end
---@return FLocString
function UUI_MainMenu_C:GetUserMapSaveAPIOfflineString() end
---@param MenuState EMainMenuState
---@param PriorState EMainMenuState
function UUI_MainMenu_C:HandleDescriptionWindowAnimation(MenuState, PriorState) end
---@param ServerSaveAPIType EServerSaveAPIType
function UUI_MainMenu_C:ShowSharedSavesOfflineWarning(ServerSaveAPIType) end
---@return FLocString
function UUI_MainMenu_C:GetSharedSaveAPIOfflineString() end
function UUI_MainMenu_C:TryShowSharedSavesOfflineAlert() end
---@param Text FLocString
function UUI_MainMenu_C:ShowWaitStringText(Text) end
---@param Window UUI_Options_C
function UUI_MainMenu_C:OpenAccessibilityOptions(Window) end
UUI_MainMenu_C['Try Show Disconnection Alert'] = function() end
function UUI_MainMenu_C:TryShowProfileLogOffAlert() end
---@param InChord FInputChord
---@return boolean
function UUI_MainMenu_C:HandleKeyEventChord(InChord) end
function UUI_MainMenu_C:TryShowKickAlert() end
---@return UWidget
function UUI_MainMenu_C:GetDefaultUserFocus() end
function UUI_MainMenu_C:ShowMainMenuButtons() end
---@return FLinearColor
function UUI_MainMenu_C:GetBGColor() end
---@return ESlateVisibility
function UUI_MainMenu_C:Get_Interface_Visibility_0() end
---@return FSlateColor
function UUI_MainMenu_C:GetHeaderColor() end
function UUI_MainMenu_C:OnFailure_7B3AE6BB4EC2994B93A5AA8377D41A71() end
---@param bGranted boolean
---@param DenyReason EOnlineUserPrivilegeDenyReason
function UUI_MainMenu_C:OnSuccess_7B3AE6BB4EC2994B93A5AA8377D41A71(bGranted, DenyReason) end
function UUI_MainMenu_C:OnFailure_7B3AE6BB4EC2994B93A5AA83F1E3D75C() end
---@param bGranted boolean
---@param DenyReason EOnlineUserPrivilegeDenyReason
function UUI_MainMenu_C:OnSuccess_7B3AE6BB4EC2994B93A5AA83F1E3D75C(bGranted, DenyReason) end
---@param PlayerController APlayerController
function UUI_MainMenu_C:OnFailure_56467364488775B10E60D88CD3873227(PlayerController) end
---@param PlayerController APlayerController
function UUI_MainMenu_C:OnSuccess_56467364488775B10E60D88CD3873227(PlayerController) end
function UUI_MainMenu_C:OnFailure_7B3AE6BB4EC2994B93A5AA83A5832413() end
---@param bGranted boolean
---@param DenyReason EOnlineUserPrivilegeDenyReason
function UUI_MainMenu_C:OnSuccess_7B3AE6BB4EC2994B93A5AA83A5832413(bGranted, DenyReason) end
function UUI_MainMenu_C:OnFailure_AAF1DEEF46E3E80168E180AD2F3F245C() end
---@param bGranted boolean
---@param DenyReason EOnlineUserPrivilegeDenyReason
function UUI_MainMenu_C:OnSuccess_AAF1DEEF46E3E80168E180AD2F3F245C(bGranted, DenyReason) end
---@param PlayerController APlayerController
function UUI_MainMenu_C:OnFailure_DBD02D6846EFAD9AF6C5B1A498DB05B0(PlayerController) end
---@param PlayerController APlayerController
function UUI_MainMenu_C:OnSuccess_DBD02D6846EFAD9AF6C5B1A498DB05B0(PlayerController) end
function UUI_MainMenu_C:OnFailure_705E0C7843DF2B168C02EC806A671B53() end
function UUI_MainMenu_C:OnSuccess_705E0C7843DF2B168C02EC806A671B53() end
---@param PlayerController APlayerController
function UUI_MainMenu_C:OnFailure_20F35731499F2C8EDB55D886F51507BE(PlayerController) end
---@param PlayerController APlayerController
function UUI_MainMenu_C:OnSuccess_20F35731499F2C8EDB55D886F51507BE(PlayerController) end
function UUI_MainMenu_C:OnFailure_8FA24DB24DB31109EB096FA77B39D939() end
---@param bGranted boolean
---@param DenyReason EOnlineUserPrivilegeDenyReason
function UUI_MainMenu_C:OnSuccess_8FA24DB24DB31109EB096FA77B39D939(bGranted, DenyReason) end
function UUI_MainMenu_C:OnFailure_D89BAC234444B1B8AB04788D845658A7() end
---@param bGranted boolean
---@param DenyReason EOnlineUserPrivilegeDenyReason
function UUI_MainMenu_C:OnSuccess_D89BAC234444B1B8AB04788D845658A7(bGranted, DenyReason) end
function UUI_MainMenu_C:OnFailure_17614A0941FA51FFD7F6519A160AB20D() end
---@param bGranted boolean
---@param DenyReason EOnlineUserPrivilegeDenyReason
function UUI_MainMenu_C:OnSuccess_17614A0941FA51FFD7F6519A160AB20D(bGranted, DenyReason) end
---@param PlayerController APlayerController
---@param ErrorString FString
function UUI_MainMenu_C:OnFailure_AD8A578043C6DC9F9236B78ACEA60610(PlayerController, ErrorString) end
---@param PlayerController APlayerController
---@param ErrorString FString
function UUI_MainMenu_C:OnSuccess_AD8A578043C6DC9F9236B78ACEA60610(PlayerController, ErrorString) end
function UUI_MainMenu_C:Construct() end
---@param MyGeometry FGeometry
---@param InDeltaTime float
function UUI_MainMenu_C:Tick(MyGeometry, InDeltaTime) end
function UUI_MainMenu_C:OnGlobalColorChange() end
---@param FromState EMainMenuState
---@param ToState EMainMenuState
---@param TransitionType EMainMenuStateTransitionType
function UUI_MainMenu_C:TransitionToMainMenuState(FromState, ToState, TransitionType) end
function UUI_MainMenu_C:StartNewSinglePlayerGame() end
function UUI_MainMenu_C:OnMultiplayerNewGameClicked() end
function UUI_MainMenu_C:OnMultiplayerContinueClicked() end
function UUI_MainMenu_C:OnSinglePlayerNewGameClicked() end
function UUI_MainMenu_C:OnSinglePlayerContinueClicked() end
function UUI_MainMenu_C:OnJoinGameTriggered() end
---@param FailureResult EJoinSessionFailureResult
function UUI_MainMenu_C:OnJoinFailure(FailureResult) end
function UUI_MainMenu_C:BndEvt__AccessibilityShortcutButton_K2Node_ComponentBoundEvent_11_OnNormalButtonClicked__DelegateSignature() end
function UUI_MainMenu_C:BndEvt__UI_OnlineLogin_K2Node_ComponentBoundEvent_3_OnLoginComplete__DelegateSignature() end
function UUI_MainMenu_C:BndEvt__UI_OnlineLogin_K2Node_ComponentBoundEvent_4_OnLoginFailure__DelegateSignature() end
function UUI_MainMenu_C:UpdateLoginButtons() end
function UUI_MainMenu_C:TransitionToMenuState() end
function UUI_MainMenu_C:TransitionToNewContinueState() end
function UUI_MainMenu_C:OnLoadGame() end
function UUI_MainMenu_C:HandlePostLogin() end
---@param NewValue int32
UUI_MainMenu_C['On Arachnophobia Mode Changed'] = function(NewValue) end
---@param FailureReason FString
function UUI_MainMenu_C:OnHostGameFailure(FailureReason) end
function UUI_MainMenu_C:Destruct() end
function UUI_MainMenu_C:OnArachWarningAccessibility() end
function UUI_MainMenu_C:OnArachWarningSkip() end
UUI_MainMenu_C['Update Arachnophobia Mode'] = function() end
function UUI_MainMenu_C:OnAccept() end
function UUI_MainMenu_C:HandlePressAnyKeyStateBegin() end
function UUI_MainMenu_C:HandleUserForcedLogin() end
function UUI_MainMenu_C:HandleUserForcedLogout() end
function UUI_MainMenu_C:CheckAracnaphobiaMessage() end
function UUI_MainMenu_C:HandleMultiplayerPrivilegeFailure() end
---@param TryToRelog boolean
function UUI_MainMenu_C:HandlePrivilegeConnectionError(TryToRelog) end
function UUI_MainMenu_C:LockMainMenuInput() end
function UUI_MainMenu_C:FreeMainMenuInput() end
function UUI_MainMenu_C:DebugRevertToPressAnyKey() end
function UUI_MainMenu_C:HandleUserProfileSystemLogout() end
function UUI_MainMenu_C:OnConnectionErrorConfirmed() end
function UUI_MainMenu_C:CheckServerDelayMessage() end
function UUI_MainMenu_C:OnAcceptWarning() end
function UUI_MainMenu_C:HandleOpeningPopups() end
---@param ContinuingGame boolean
function UUI_MainMenu_C:HandlePublicOrPrivateQuestion(ContinuingGame) end
function UUI_MainMenu_C:CreateNonPasswordGame() end
---@param GameTypeMode ESaveLoadGameTypeMode
function UUI_MainMenu_C:OpenLoadScreen(GameTypeMode) end
function UUI_MainMenu_C:HandleSaveConversionBegin() end
---@param RequiresLoad boolean
function UUI_MainMenu_C:CheckIfSaveConversionComplete(RequiresLoad) end
function UUI_MainMenu_C:HandleConvertSavesComplete() end
function UUI_MainMenu_C:HandleUpdateRequriedMultiplayerFailure() end
function UUI_MainMenu_C:HandleCreatePasswordGameBegin() end
---@param UserText FString
function UUI_MainMenu_C:OnPasswordCreated(UserText) end
function UUI_MainMenu_C:OnCancel() end
function UUI_MainMenu_C:HandleWelcomeAccept() end
function UUI_MainMenu_C:CheckEarlyAccessMessage() end
function UUI_MainMenu_C:CancelChangeAccessibilitySettings() end
function UUI_MainMenu_C:AcceptChangeAccessibilitySettings() end
function UUI_MainMenu_C:CheckAccessibilityMessage() end
function UUI_MainMenu_C:FinishOpeningPopups() end
---@param Sender UWindowWidget
function UUI_MainMenu_C:HandleAccessibilityOptionsClosed(Sender) end
function UUI_MainMenu_C:HandleSharedOrLocalWorldBegin() end
function UUI_MainMenu_C:BndEvt__UI_MainMenu_UI_Buttons_MainMenu_K2Node_ComponentBoundEvent_15_OnSinglePlayerClicked__DelegateSignature() end
function UUI_MainMenu_C:BndEvt__UI_MainMenu_UI_Buttons_MainMenu_K2Node_ComponentBoundEvent_16_OnMultiplayerClicked__DelegateSignature() end
function UUI_MainMenu_C:BndEvt__UI_MainMenu_UI_Buttons_MainMenu_K2Node_ComponentBoundEvent_17_OnCreditsClicked__DelegateSignature() end
function UUI_MainMenu_C:BndEvt__UI_MainMenu_UI_Buttons_MainMenu_K2Node_ComponentBoundEvent_18_OnOptionsClicked__DelegateSignature() end
function UUI_MainMenu_C:BndEvt__UI_MainMenu_UI_Buttons_MainMenu_K2Node_ComponentBoundEvent_19_OnTestLevelsClicked__DelegateSignature() end
function UUI_MainMenu_C:BndEvt__UI_MainMenu_UI_Buttons_MainMenu_K2Node_ComponentBoundEvent_20_OnQuitClicked__DelegateSignature() end
function UUI_MainMenu_C:BndEvt__UI_MainMenu_NewContinueButtonOptionsNew_K2Node_ComponentBoundEvent_8_OnBackClicked__DelegateSignature() end
function UUI_MainMenu_C:BndEvt__UI_MainMenu_HostJoinButtonOptionsNew_K2Node_ComponentBoundEvent_21_OnHostClicked__DelegateSignature() end
function UUI_MainMenu_C:BndEvt__UI_MainMenu_HostJoinButtonOptionsNew_K2Node_ComponentBoundEvent_23_OnBackClicked__DelegateSignature() end
function UUI_MainMenu_C:BndEvt__UI_MainMenu_HostJoinButtonOptionsNew_K2Node_ComponentBoundEvent_22_OnJoinClicked__DelegateSignature() end
function UUI_MainMenu_C:BndEvt__UI_MainMenu_NewContinueButtonOptions_K2Node_ComponentBoundEvent_28_OnContinueClicked__DelegateSignature() end
function UUI_MainMenu_C:BndEvt__UI_MainMenu_NewContinueButtonOptions_K2Node_ComponentBoundEvent_29_OnNewGameClicked__DelegateSignature() end
---@param SharedSavesSelected boolean
function UUI_MainMenu_C:OnSaveStyleSelected(SharedSavesSelected) end
function UUI_MainMenu_C:OnSaveStyleCanceled() end
function UUI_MainMenu_C:ManageMaxSharedSaves() end
function UUI_MainMenu_C:BndEvt__UI_MainMenu_ChangeProfileButton_K2Node_ComponentBoundEvent_0_OnNormalButtonClicked__DelegateSignature() end
function UUI_MainMenu_C:HandleProfileChange() end
---@param SharedSaveHostToJoin FString
function UUI_MainMenu_C:OpenServerBrowser(SharedSaveHostToJoin) end
function UUI_MainMenu_C:HandleMultiplayerButtonClicked() end
function UUI_MainMenu_C:BndEvt__UI_MainMenu_NewContinueButtonOptions_K2Node_ComponentBoundEvent_5_OnNewPlaygroundClicked__DelegateSignature() end
function UUI_MainMenu_C:OnSinglePlayerNewPlaygroundClicked() end
function UUI_MainMenu_C:OnMultiplayerNewPlaygroundClicked() end
---@param SharedSaveAPIStatus EServerSaveAPIStatus
---@param ServerSaveAPI EServerSaveAPIType
function UUI_MainMenu_C:OnServerSaveStatusUpdate(SharedSaveAPIStatus, ServerSaveAPI) end
function UUI_MainMenu_C:BndEvt__UI_MainMenu_NewContinueButtonOptions_K2Node_ComponentBoundEvent_6_OnPlaygroundContinueClicked__DelegateSignature() end
function UUI_MainMenu_C:BndEvt__UI_MainMenu_NewContinueButtonOptions_K2Node_ComponentBoundEvent_7_OnPlaygroundCommunityClicked__DelegateSignature() end
function UUI_MainMenu_C:OnMultiplayerContinuePlaygroundClicked() end
function UUI_MainMenu_C:OnSinglePlayerContinuePlaygroundClicked() end
function UUI_MainMenu_C:OnSinglePlayerPlaygroundCommunityClicked() end
function UUI_MainMenu_C:OnMultiplayerPlaygroundCommunityClicked() end
---@param ButtonDescriptionTitle FLocString
---@param ButtonDescription FLocString
---@param IsPlaygroundButton boolean
function UUI_MainMenu_C:BndEvt__UI_MainMenu_NewContinueButtonOptions_K2Node_ComponentBoundEvent_9_OnButtonHoveredOrFocused__DelegateSignature(ButtonDescriptionTitle, ButtonDescription, IsPlaygroundButton) end
function UUI_MainMenu_C:CheckAndCacheUserPrivilege() end
UUI_MainMenu_C['Handle Purchase Required Failure'] = function() end
function UUI_MainMenu_C:HandleCrossplayConfirmationWindow() end
function UUI_MainMenu_C:CreateAccountLinkWidget() end
function UUI_MainMenu_C:DestroyAccountLinkWidget() end
---@param Success boolean
function UUI_MainMenu_C:OnAccountLinkWidgetClosed(Success) end
function UUI_MainMenu_C:ResetAllActivities() end
---@param Reason EOnlineUserPrivilegeDenyReason
function UUI_MainMenu_C:HandlePrivilageCheck(Reason) end
function UUI_MainMenu_C:ProcessContinueActivity() end
function UUI_MainMenu_C:HandleAgeRequirementFailure() end
function UUI_MainMenu_C:ProcessCrossplayToggleFlow() end
function UUI_MainMenu_C:BndEvt__UI_MainMenu_AccessibilityShortcutButton_1_K2Node_ComponentBoundEvent_1_OnNormalButtonClicked__DelegateSignature() end
function UUI_MainMenu_C:BndEvt__UI_MainMenu_DisableCrossplayShortcutButton_K2Node_ComponentBoundEvent_13_OnNormalButtonClicked__DelegateSignature() end
---@param Intent ECrossplayResumeIntent
function UUI_MainMenu_C:ToggleCrossplayAndTriggerLogin(Intent) end
---@param CrossplaySettingChanged boolean
function UUI_MainMenu_C:Event_OnOptionsWindowClosed(CrossplaySettingChanged) end
function UUI_MainMenu_C:UpdateCrossplayToggleVisibility() end
---@param NewValue boolean
UUI_MainMenu_C['Crossplay Enable Changed'] = function(NewValue) end
function UUI_MainMenu_C:BndEvt__UI_MainMenu_EnableCrossplayMainMenuButton_K2Node_ComponentBoundEvent_2_OnNormalButtonClicked__DelegateSignature() end
function UUI_MainMenu_C:BndEvt__UI_MainMenu_DisableCrossplayMainMenuButton_K2Node_ComponentBoundEvent_10_OnNormalButtonClicked__DelegateSignature() end
function UUI_MainMenu_C:CreateSteamAccountLinkWidget() end
function UUI_MainMenu_C:OnAccountLinkPlayOffline() end
function UUI_MainMenu_C:OnSteamAccountLinkWidgetPlayOffline() end
function UUI_MainMenu_C:OnSteamAccountLinkWidgetAccepted() end
function UUI_MainMenu_C:OnSteamAccountLinkWidgetClosed() end
function UUI_MainMenu_C:DestroySteamAccountLinkWidget() end
---@param EntryPoint int32
function UUI_MainMenu_C:ExecuteUbergraph_UI_MainMenu(EntryPoint) end


